name: validprot
channels:
  - plotly
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - anyio=3.6.2
  - appnope=0.1.3
  - argon2-cffi=21.3.0
  - argon2-cffi-bindings=21.2.0
  - asttokens=2.2.1
  - attrs=22.2.0
  - babel=2.12.1
  - backcall=0.2.0
  - backports=1.0
  - backports.functools_lru_cache=1.6.4
  - beautifulsoup4=4.11.2
  - biopython=1.81
  - blas=1.0
  - bleach=6.0.0
  - bottleneck=1.3.5
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - ca-certificates=2022.12.7
  - certifi=2022.12.7
  - cffi=1.15.1
  - charset-normalizer=2.1.1
  - cryptography=38.0.4
  - debugpy=1.6.6
  - decorator=5.1.1
  - defusedxml=0.7.1
  - entrypoints=0.4
  - executing=1.2.0
  - flit-core=3.8.0
  - hmmer=3.3.2
  - idna=3.4
  - importlib-metadata=6.0.0
  - importlib_metadata=6.0.0
  - importlib_resources=5.12.0
  - ipykernel=6.15.0
  - ipython=8.11.0
  - ipython_genutils=0.2.0
  - jedi=0.18.2
  - jinja2=3.1.2
  - joblib=1.2.0
  - json5=0.9.5
  - jsonschema=4.17.3
  - jupyter_client=8.0.3
  - jupyter_core=5.2.0
  - jupyter_events=0.6.3
  - jupyter_server=2.4.0
  - jupyter_server_terminals=0.4.4
  - jupyterlab=3.5.0
  - jupyterlab_pygments=0.2.2
  - jupyterlab_server=2.20.0
  - kaleido-core=0.2.1
  - libblas=3.9.0
  - libcblas=3.9.0
  - libcxx=15.0.7
  - libffi=3.4.2
  - libgfortran=5.0.0
  - libgfortran5=12.2.0
  - liblapack=3.9.0
  - libopenblas=0.3.21
  - libsodium=1.0.18
  - llvm-openmp=15.0.7
  - markupsafe=2.1.2
  - mathjax=2.7.7
  - matplotlib-inline=0.1.6
  - mistune=2.0.5
  - nbclassic=0.5.2
  - nbclient=0.7.2
  - nbconvert=7.2.9
  - nbconvert-core=7.2.9
  - nbconvert-pandoc=7.2.9
  - nbformat=5.7.3
  - ncurses=6.4
  - nest-asyncio=1.5.6
  - notebook=6.5.3
  - notebook-shim=0.2.2
  - numexpr=2.8.4
  - numpy=1.24.2
  - openssl=1.1.1t
  - packaging=22.0
  - pandas=1.5.3
  - pandoc=2.19.2
  - pandocfilters=1.5.0
  - parso=0.8.3
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pip=23.0.1
  - pkgutil-resolve-name=1.3.10
  - platformdirs=3.1.0
  - plotly=5.13.1
  - prometheus_client=0.16.0
  - prompt-toolkit=3.0.38
  - prompt_toolkit=3.0.38
  - psutil=5.9.4
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pycparser=2.21
  - pygments=2.14.0
  - pyopenssl=23.0.0
  - pyrsistent=0.19.3
  - pysocks=1.7.1
  - python=3.10.9
  - python-dateutil=2.8.2
  - python-fastjsonschema=2.16.3
  - python-json-logger=2.0.7
  - python-kaleido=0.2.1
  - python_abi=3.10
  - pytz=2022.7
  - pyyaml=6.0
  - pyzmq=25.0.0
  - readline=8.2
  - requests=2.28.2
  - rfc3339-validator=0.1.4
  - rfc3986-validator=0.1.1
  - scikit-learn=1.2.1
  - scipy=1.9.3
  - send2trash=1.8.0
  - setuptools=65.6.3
  - six=1.16.0
  - sniffio=1.3.0
  - soupsieve=2.3.2.post1
  - sqlite=3.40.1
  - stack_data=0.6.2
  - tenacity=8.0.1
  - terminado=0.17.1
  - threadpoolctl=3.1.0
  - tinycss2=1.2.1
  - tk=8.6.12
  - tomli=2.0.1
  - tornado=6.2
  - traitlets=5.9.0
  - typing-extensions=4.4.0
  - typing_extensions=4.4.0
  - tzdata=2022g
  - urllib3=1.26.14
  - wcwidth=0.2.6
  - webencodings=0.5.1
  - websocket-client=1.5.1
  - wheel=0.38.4
  - xz=5.2.10
  - yaml=0.2.5
  - zeromq=4.3.4
  - zipp=3.15.0
  - zlib=1.2.13
prefix: /opt/anaconda3/envs/validprot
